export const GET_OFFERS_REQUEST = "GET_OFFERS_REQUEST";
export const GET_OFFERS_SUCCESS = "GET_OFFERS_SUCCESS";
export const GET_OFFERS_ERROR = "GET_OFFERS_ERROR";
export const SHOW_FULL_OFFERS = "SHOW_FULL_OFFERS";
